### PR TITLE
[tshev] use cpp overloadings

### PR DESCRIPTION
**Pull request by tshev**

### CODE REVIEW

**Comment by tshev** [comment]
@psoberoi There are a few lines, which led to a few incorrect measurements.

**Comment by tshev** [comment]
@psoberoi this PR removes implicit conversions for `srt` and `pow`.
[transformbench.tshev.0.txt](https://github.com/psoberoi/stepanov-conversations-course/files/3262240/transformbench.tshev.0.txt)
[transformbench.tshev.1.txt](https://github.com/psoberoi/stepanov-conversations-course/files/3262241/transformbench.tshev.1.txt)

**Comment by psoberoi** [comment]
Sorry for the delay in responding. The change looks good, but can you explain a little more how it prevents implicit conversions?

**Comment by psoberoi** [comment]
Ah, you mean it's implicitly converting to double without std::

It's interesting how double is often faster than float. I guess most libraries are better optimized for doubles.

**Comment by tshev** [comment]
@psoberoi the idea is right. There are several similar cases. For example, in line `transformbench.cpp:142:18:` we had an implicit conversion from long to int. I've found several similar cases, then I've asked a compiler for help. Here is the output from clang: https://gist.github.com/tshev/e9b818047a08fbfca9dbae358925e54b

Formally, C does not have support of overloading , so we can have only one function prototype with the same name(we can break this with `varargs`, but it is a different story). But C has a number of prefixes for popular math functions. They help us to deal with different argument types. For example, https://en.cppreference.com/w/c/numeric/math/abs. C++ supports function overloading, so we can use only one function name for different argument types. But `cmath` header uses `math.h`, so it is to call a C function from C++ when we forget to a namespace specifier during a function call. `using namespace std;` may help too, but I don't like to use this line at any point of my code.

**Pull request merged**
